title: Erq'owy Blog
description: Nie ma ślimaków i ślimakowych. Są tylko liście. A kto sądzi inaczej jest w błędzie.
baseurl: ""
url: "http://erq.tawerna.net" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
